const restaurantData = [
    { restaurantName: "Spicy Bites", cuisine: "Indian", stars: "3.8", deliveryTime: "30 mins" },
    { restaurantName: "Ocean's Delight", cuisine: "Seafood", stars: "4.5", deliveryTime: "25 mins" },
    { restaurantName: "Mountain Feast", cuisine: "Continental", stars: "3.6", deliveryTime: "35 mins" },
    { restaurantName: "Urban Tadka", cuisine: "Fusion", stars: "4.3", deliveryTime: "20 mins" },
    { restaurantName: "Golden Spoon", cuisine: "Italian", stars: "4.7", deliveryTime: "40 mins" },
    { restaurantName: "Flavor Town", cuisine: "Mexican", stars: "4.1", deliveryTime: "30 mins" },
    { restaurantName: "Curry House", cuisine: "Thai", stars: "3.9", deliveryTime: "25 mins" },
    { restaurantName: "Grill & Chill", cuisine: "BBQ", stars: "4.8", deliveryTime: "45 mins" },
    { restaurantName: "Taste Paradise", cuisine: "Chinese", stars: "4.0", deliveryTime: "30 mins" },
    { restaurantName: "Fusion Fiesta", cuisine: "Multi-Cuisine", stars: "4.9", deliveryTime: "50 mins" },
    { restaurantName: "Sushi World", cuisine: "Japanese", stars: "4.2", deliveryTime: "30 mins" },
    { restaurantName: "Mediterranean Bliss", cuisine: "Mediterranean", stars: "4.6", deliveryTime: "35 mins" },
    { restaurantName: "Vegan Delights", cuisine: "Vegan", stars: "4.4", deliveryTime: "25 mins" },
    { restaurantName: "Burger Haven", cuisine: "American", stars: "3.5", deliveryTime: "20 mins" },
    { restaurantName: "Pasta Palace", cuisine: "Italian", stars: "4.3", deliveryTime: "30 mins" },
    { restaurantName: "Taco Town", cuisine: "Mexican", stars: "3.7", deliveryTime: "25 mins" },
    { restaurantName: "Sizzling Wok", cuisine: "Chinese", stars: "4.1", deliveryTime: "35 mins" },
    { restaurantName: "BBQ Bliss", cuisine: "BBQ", stars: "4.5", deliveryTime: "40 mins" },
    { restaurantName: "Healthy Bites", cuisine: "Vegan", stars: "4.0", deliveryTime: "20 mins" },
    { restaurantName: "Pizza Planet", cuisine: "Italian", stars: "4.6", deliveryTime: "30 mins" },
    { restaurantName: "Curry Corner", cuisine: "Indian", stars: "3.9", deliveryTime: "25 mins" },
    { restaurantName: "Seafood Shack", cuisine: "Seafood", stars: "4.7", deliveryTime: "35 mins" },
    { restaurantName: "Grill Masters", cuisine: "BBQ", stars: "4.8", deliveryTime: "45 mins" },
    { restaurantName: "Sushi Express", cuisine: "Japanese", stars: "4.3", deliveryTime: "30 mins" },
    { restaurantName: "Mediterranean Magic", cuisine: "Mediterranean", stars: "4.5", deliveryTime: "35 mins" },
    { restaurantName: "Fusion Flavors", cuisine: "Fusion", stars: "4.0", deliveryTime: "20 mins" },
    { restaurantName: "Spice Symphony", cuisine: "Indian", stars: "3.6", deliveryTime: "30 mins" },
    { restaurantName: "Ocean Breeze", cuisine: "Seafood", stars: "4.4", deliveryTime: "25 mins" },
    { restaurantName: "Mountain Grill", cuisine: "Continental", stars: "3.8", deliveryTime: "35 mins" },
    { restaurantName: "Urban Eats", cuisine: "Fusion", stars: "4.2", deliveryTime: "20 mins" },
    { restaurantName: "Golden Fork", cuisine: "Italian", stars: "4.7", deliveryTime: "40 mins" },
    { restaurantName: "Flavor Fiesta", cuisine: "Mexican", stars: "4.1", deliveryTime: "30 mins" },
    { restaurantName: "Curry Delight", cuisine: "Thai", stars: "3.9", deliveryTime: "25 mins" },
    { restaurantName: "Grill House", cuisine: "BBQ", stars: "4.6", deliveryTime: "45 mins" },
    { restaurantName: "Taste Haven", cuisine: "Chinese", stars: "4.0", deliveryTime: "30 mins" },
    { restaurantName: "Fusion Feast", cuisine: "Multi-Cuisine", stars: "4.9", deliveryTime: "50 mins" },
    { restaurantName: "Sushi Delight", cuisine: "Japanese", stars: "4.2", deliveryTime: "30 mins" },
    { restaurantName: "Mediterranean Treats", cuisine: "Mediterranean", stars: "4.6", deliveryTime: "35 mins" },
    { restaurantName: "Vegan Paradise", cuisine: "Vegan", stars: "4.4", deliveryTime: "25 mins" },
    { restaurantName: "Burger Bliss", cuisine: "American", stars: "3.4", deliveryTime: "20 mins" },
    { restaurantName: "Pasta Delight", cuisine: "Italian", stars: "4.3", deliveryTime: "30 mins" },
    { restaurantName: "Taco Fiesta", cuisine: "Mexican", stars: "3.7", deliveryTime: "25 mins" },
    { restaurantName: "Wok Wonders", cuisine: "Chinese", stars: "4.1", deliveryTime: "35 mins" },
    { restaurantName: "BBQ Heaven", cuisine: "BBQ", stars: "4.5", deliveryTime: "40 mins" },
    { restaurantName: "Healthy Eats", cuisine: "Vegan", stars: "4.0", deliveryTime: "20 mins" },
    { restaurantName: "Pizza Delight", cuisine: "Italian", stars: "4.6", deliveryTime: "30 mins" },
    { restaurantName: "Curry Magic", cuisine: "Indian", stars: "3.9", deliveryTime: "25 mins" },
    { restaurantName: "Seafood Paradise", cuisine: "Seafood", stars: "4.7", deliveryTime: "35 mins" },
    { restaurantName: "Grill Delight", cuisine: "BBQ", stars: "4.8", deliveryTime: "45 mins" },
    { restaurantName: "Sushi Bliss", cuisine: "Japanese", stars: "4.3", deliveryTime: "30 mins" },
];

export default restaurantData;